name = "RCG_DFTK_paper"
uuid = "4591cc44-79b3-48da-95d1-a9603d3c515a"
authors = ["Jonas PÃ¼schel <jonas.pueschel@uni-a.de>"]
version = "0.2.0"

[deps]
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PseudoPotentialData = "5751a51d-ac76-4487-a056-413ecf6fbe19"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
DFTK = "0.7.17"
LinearAlgebra = "1.11.0"
PlotlyJS = "0.18.17"
Printf = "1.11.0"
PseudoPotentialData = "0.2.4"
TimerOutputs = "0.5.29"
